version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "diamonds/app/Dockerfile",
    "level-based-segments/app/Dockerfile"
  ]

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"